SELECT
	T1.IDSOLICITUD,
	COALESCE(T6.ANTIGUEDADDOMICILIO, '\0') AS AntiguedadDomicilio,
	COALESCE(T18.APELLIDOMATERNO, '\0') AS ApellidoMaternoSolicitud,
	COALESCE(T18.APELLIDOPATERNO, '\0') AS ApellidoPaternoSolicitud,
	COALESCE(T6.CARGOUOCUPACIONDELSOLICITANTE, '\0') AS CargoUOcupacionDelSolicitante,
	COALESCE(CAST(T3.SCOREADICIONAL AS VARCHAR2(10)), '\0') AS CodigoPostal,
	COALESCE(T16.ESTADOCEDULA, '\0') AS ColoniaFraccionamiento,
	'\0' curp,
	COALESCE(T18.DIRECCION, '\0') AS DelegacionMunicipio,
	COALESCE(T10.POSEEOBSERVACION3, '\0') AS DireccionDistintaalINE,
	--COALESCE(T4.FECHAULTRENEGOCIACION, '\0') AS EmpleadoFechaIngreso,
	COALESCE(CASE WHEN LENGTH(TRIM(SUBSTR(T4.FECHAULTRENEGOCIACION ,1,8))) = 8 THEN to_char(TO_DATE(T4.FECHAULTRENEGOCIACION ,'dd-mm-yyyy'),'yyyymmdd') ELSE NULL END , '\0') AS EmpleadoFechaIngreso,
	CASE WHEN T18.DIRECCIONRESTO = 'EMPLEADO' THEN '1' ELSE '0' END AS EmpleadoFlag,
	COALESCE(T5.PROMOTOR, '\0') AS EmpleadoNombreEmpresa,
	COALESCE(T13.DETALLE1MONTOPESOS, '\0') AS EmpleadoNumEmpresa,
	COALESCE(T18.DIRECCIONCIUDAD, '\0') AS Estado,
	COALESCE(T6.ESTADOCIVIL, '\0') AS EstadoCivil,
	--COALESCE(T6.FECHADEINGRESOALTRABAJO, '\0') AS Fechadeingresoaltrabajo,
	COALESCE(CASE WHEN LENGTH(TRIM(SUBSTR(T6.FECHADEINGRESOALTRABAJO ,1,8))) = 8 THEN to_char(TO_DATE(T6.FECHADEINGRESOALTRABAJO ,'dd-mm-yyyy'),'yyyymmdd') ELSE NULL END , '\0') AS Fechadeingresoaltrabajo,
	--COALESCE(T16.BOLETINLABORALFECHARECIENTE, '\0') AS FechadeIngresoEmpleoAnterior,
	COALESCE(CASE WHEN LENGTH(TRIM(SUBSTR(T16.BOLETINLABORALFECHARECIENTE ,1,8))) = 8 THEN to_char(TO_DATE(T16.BOLETINLABORALFECHARECIENTE ,'dd-mm-yyyy'),'yyyymmdd') ELSE NULL END , '\0') AS FechadeIngresoEmpleoAnterior,
	--COALESCE(T6.FECHADENACIMIENTO, '\0') AS Fechadenacimiento,
	COALESCE(CASE WHEN LENGTH(TRIM(SUBSTR(T6.FECHADENACIMIENTO ,1,8))) = 8 THEN to_char(TO_DATE(T6.FECHADENACIMIENTO ,'dd-mm-yyyy'),'yyyymmdd') ELSE NULL END , '\0') AS Fechadenacimiento,
	--COALESCE(T16.QUIEBRAFECHARECIENTE, '\0') AS FechadeSalidaEmpleoAnterior,
	COALESCE(CASE WHEN LENGTH(TRIM(SUBSTR(T16.QUIEBRAFECHARECIENTE ,1,8))) = 8 THEN to_char(TO_DATE(T16.QUIEBRAFECHARECIENTE ,'dd-mm-yyyy'),'yyyymmdd') ELSE NULL END , '\0') AS FechadeSalidaEmpleoAnterior,
	'\0' AS FlagAutoAutenticacion,
	'\0' AS FlagHipotecarioAutenticacion,
	'\0' AS FlagTCAutenticacion,
	COALESCE(SUBSTR(T6.SEXO,1,1), '\0') AS Genero,
	COALESCE(T6.GIROOACTIVIDADDELAEMPRESA, '\0') AS GiroOActividadDeLaEmpresa,
	COALESCE(T6.NACIONALIDAD, '\0') AS Nacionalidad,
	COALESCE(T6.NIVELESTUDIOS, '\0') AS NivelEstudios,
	COALESCE(T18.NOMBRES, '\0') AS NombreSolicitud,
	'Mexico' AS Pais,
	COALESCE(T6.RENTA, '\0') AS Renta,
	COALESCE(T4.DIASMORARENEGOCIAR, '\0') AS RFMAnioNac,
	COALESCE(T13.DETALLE1TIPODOCUMENTO, '\0') AS RFMApellidoMaterno,
	COALESCE(T13.DETALLE1TIPOCREDITO, '\0') AS RFMApellidoPaterno,
	COALESCE(T4.PORCAVANCE, '\0') AS RFMCoeficiente,
	COALESCE(T14.ANUALANTERIOR, '\0') AS RFMConTDC,
	COALESCE(CAST(T8.DIASMORAAVAL AS VARCHAR2(10)), '\0') AS RFMCP,
	COALESCE(T1.STRING1, '\0') AS RFMFlag,
	COALESCE(T18.INFOCONYUGE, '\0') AS RFMGrupo,
	COALESCE(T13.DETALLE1LOCALIDAD, '\0') AS RFMNombre,
	COALESCE(CAST(T20.MONTOTOTALUF AS VARCHAR2(10)), '\0') AS RFMPromCompraMensual,
	COALESCE(CAST(T20.CANTIDADTELEFONOSFIJOS AS VARCHAR2(10)), '\0') AS RFMScoreTrans,
	COALESCE(CAST(T4.PORCSOBREGIRO AS VARCHAR2(10)), '\0') AS RFMVariable1,
	COALESCE(CAST(T20.CANTIDADVEHICULOS AS VARCHAR2(10)), '\0') AS RFMVariable2,
	COALESCE(T18.DIRECCIONNUMERO, '\0') AS TCAprecio,
	COALESCE(T6.TIPODEVIVIENDA, '\0') AS TipoDeVivienda,
	'\0' AS Ult4DigitosTDC,
	2 AS CanalEvaluacion,
	2 AS CanalOrigen,
	to_char(T1.FECHAREGISTRO ,'yyyymmdd') AS FechaEvaluacion,
	'\0' FechaPreEvaluacion,
	'\0' FlagEL,
	'\0' IDCategoria,
	'\0' Llamada,
	'\0' MontoSolicitado,
	COALESCE(T5.SUCURSALAPERTURA, '\0') AS SucursalApertura
FROM TB_MRRES_INPUTANTECEDENTE T1
	LEFT JOIN TB_MRRES_ANTCOMOADICIONAL T3 ON T1.IDSOLICITUD = T3.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T3.FECHAREGISTRO AS TIMESTAMP) 
	LEFT JOIN TB_MRRES_ANTCOMOCLIENTEOTRACTA T4 ON T1.IDSOLICITUD = T4.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T4.FECHAREGISTRO AS TIMESTAMP) 
	LEFT JOIN TB_MRRES_ANTSOLICITUD T5 ON T1.IDSOLICITUD = T5.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T5.FECHAREGISTRO AS TIMESTAMP) 
	LEFT JOIN TB_MRRES_ANTPARTICULARES T6 ON T1.IDSOLICITUD = T6.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T6.FECHAREGISTRO AS TIMESTAMP)
	LEFT JOIN TB_MRRES_CODEUDOR T8 ON T1.IDSOLICITUD = T8.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T8.FECHAREGISTRO AS TIMESTAMP)
	LEFT JOIN TB_MRRES_OBSERVACIONES T10 ON T1.IDSOLICITUD = T10.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T10.FECHAREGISTRO AS TIMESTAMP)
	LEFT JOIN TB_MRRES_TRANSUNIONANTBURO T13 ON T1.IDSOLICITUD = T13.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T13.FECHAREGISTRO AS TIMESTAMP) 
	LEFT JOIN TB_MRRES_TRANSUNIONCOMEXEXPORT T14 ON T1.IDSOLICITUD = T14.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T14.FECHAREGISTRO AS TIMESTAMP)
	LEFT JOIN TB_MRRES_TRANSUNIONCONTROL T16 ON T1.IDSOLICITUD = T16.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T16.FECHAREGISTRO AS TIMESTAMP)
	LEFT JOIN TB_MRRES_TRANSUNIONPARTICULAR T18 ON T1.IDSOLICITUD = T18.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T18.FECHAREGISTRO AS TIMESTAMP)
	LEFT JOIN TB_MRRES_TRANSUNIONSCORE T20 ON T1.IDSOLICITUD = T20.IDSOLICITUD AND CAST(T1.FECHAREGISTRO AS TIMESTAMP) = CAST(T20.FECHAREGISTRO AS TIMESTAMP)
WHERE 
	T1.IDSOLICITUD in (
		S0L1C1TUD3S
			)
ORDER BY T1.IDSOLICITUD
;
